name: CI/CD Pipeline via SSH Deployment

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      # ✅ 디버깅 코드 추가 (SSH Key가 제대로 전달되는지 확인)
      - name: Debug SSH Key
        run: echo "${{ secrets.SSH_PRIVATE_KEY }}" | wc -l

      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd SOF-Backend
            git pull origin main
            npm install
            npx prisma migrate deploy
            pm2 restart all